from __future__ import annotations

import json
import os
import textwrap

from models.schemas import PlatformFormats
from core.utils import get_llm
from core.logger import get_logger

logger = get_logger("exporter")


def _truncate(text: str, max_chars: int = 3000) -> str:
    """Safely truncate text for prompts while keeping it meaningful."""
    return text[:max_chars] if len(text) > max_chars else text


async def format_for_platforms(title: str, content: str) -> PlatformFormats:
    """Generate platform-adapted content for 5 platforms.

    Each platform version is 200-300 words, uniquely adapted.
    Returns valid JSON with proper escaping.
    """
    # Shortcut fallback if no API key
    if not os.environ.get("GROQ_API_KEY"):
        return _make_fallback(title, content)

    from langchain_core.prompts import ChatPromptTemplate
    llm = get_llm(temperature=0.6, max_tokens=4000)

    truncated_content = _truncate(content, 2500)

    prompt = ChatPromptTemplate.from_messages([
        ("system", "You are a multi-platform content repurposer. Return ONLY valid JSON."),
        ("human", textwrap.dedent("""\
            Convert this blog into platform formats.

            Original Title: {title}
            Original Content: {content}

            Return ONLY valid JSON:

            {{
              "medium": "string",
              "linkedin": "string",
              "wordpress": "string",
              "devto": "string",
              "hashnode": "string"
            }}

            Rules:
            - Each field max 200-300 words
            - No markdown formatting in values
            - No explanation outside JSON
            - Escape quotes properly
            - Valid JSON only — parsable by json.loads()
            - medium: storytelling hook, personal insights
            - linkedin: professional tone, bold hook, 2-3 emojis, hashtags
            - wordpress: SEO meta comments then content
            - devto: YAML frontmatter then content
            - hashnode: TL;DR bullets then content
        """)),
    ])

    # Strategy 1: Structured output
    try:
        structured_llm = llm.with_structured_output(PlatformFormats)
        result = await structured_llm.ainvoke(
            prompt.format_messages(title=title, content=truncated_content)
        )
        if result is not None:
            logger.info("Platform formats generated (structured): %s...", title[:40])
            return result
    except Exception as err:
        logger.warning("Structured platform output failed: %s", err)

    # Strategy 2: Raw LLM + JSON parse
    try:
        raw = await llm.ainvoke(
            prompt.format_messages(title=title, content=truncated_content)
        )
        text = raw.content
        if "{" in text:
            json_str = text[text.index("{"):text.rindex("}") + 1]
            data = json.loads(json_str)
            result = PlatformFormats(**data)
            logger.info("Platform formats generated (parsed): %s...", title[:40])
            return result
    except Exception as err:
        logger.warning("Platform JSON parse failed: %s", err)

    # Strategy 3: Fallback
    logger.warning("Using fallback platform formats for: %s...", title[:40])
    return _make_fallback(title, content)


def _make_fallback(title: str, content: str) -> PlatformFormats:
    """Create decent fallback platform versions from the original content."""
    clean = content.replace("# ", "").replace("## ", "").replace("### ", "")
    short = clean[:800]

    return PlatformFormats(
        medium=(
            f"{title}\n\n"
            f"{short}\n\n"
            f"If this resonated with you, follow for more insights on AI and content marketing. "
            f"Originally published on Blogy."
        ),
        linkedin=(
            f"🚀 {title}\n\n"
            f"{short[:500]}\n\n"
            f"💡 Key Takeaways:\n"
            f"• AI-powered blogging saves 70% of content creation time\n"
            f"• SEO-optimized content drives sustainable organic traffic\n"
            f"• Multi-platform publishing maximizes reach\n\n"
            f"What's your experience with AI content tools? 👇\n\n"
            f"#AI #SEO #ContentMarketing #Blogging #MarTech"
        ),
        wordpress=(
            f"<!-- Meta Title: {title[:60]} -->\n"
            f"<!-- Meta Description: {clean[:155]} -->\n"
            f"<!-- Focus Keyword: {title.split()[0]} -->\n\n"
            f"{short}\n\n"
            f"About the Author: This post was generated by Blogy's AI Blog Engine."
        ),
        devto=(
            f"---\n"
            f"title: {title}\n"
            f"published: true\n"
            f"tags: seo, ai, blogging, contentmarketing\n"
            f"---\n\n"
            f"{short}\n\n"
            f"Built with Blogy — India's AI Blog Automation Platform."
        ),
        hashnode=(
            f"TL;DR\n\n"
            f"- AI blog automation saves time and money\n"
            f"- SEO-optimized content ranks better on Google\n"
            f"- Multi-platform publishing maximizes content ROI\n\n"
            f"{title}\n\n"
            f"{short}\n\n"
            f"What do you think about AI-powered content creation? "
            f"Share your experience in the comments!"
        ),
    )
